### ISSUE TITLE
Updating plugin on test site

### ISSUE THREAD

**Issue by davallerr** [mmarquiscreative/AGX_OHT_Mach2_AngularJS#1]
Hi @see8ch, is there a way for us to update the plugin on the test site ourselves, or will we need to let you know?

Thanks,
David

**Comment by see8ch** [comment]
No problem, I set up an FTP account for you. Details below...

- SFTP Host: `agcorp.sftp.wpengine.com`
- Port: `2222`
- User: `agcorp-davallerr`
- Password: `su8LL2WgvBWBKK`
