### ISSUE TITLE
Updating plugin on demo site

### ISSUE THREAD

**Issue by davallerr** [mmarquiscreative/AGX_OHT_Mach2_AngularJS#5]
Hi @see8ch, thanks for adding the plugin to http://demo.merriweather.wpengine.com/. Can we get SFTP access to update the plugin there? Looks like the section displays correctly on the page, but there are some new style conflicts within the quiz to sort out as well as the other issues like the 500 error on the results page.

Thanks!

**Comment by see8ch** [comment]
No problem, here you go...

- Host: `merriweather.sftp.wpengine.com `
- Port: `2222`
- User: `merriweather-davallerr`
- Pass: `zisfuw-duqho8-herdEw`
