### ISSUE TITLE
staging site for agxhearing.com

### ISSUE THREAD

**Issue by davallerr** [mmarquiscreative/AGX_OHT_Mach2_AngularJS#6]
Hey @see8ch, is there a staging site set up for agxhearing.com where we can make sure the plugin works well on that theme? Thanks!

**Comment by see8ch** [comment]
There is a new staging environment available here: http://www-agxhearing-com.agcorp.staging.wpengine.com/wp-admin/

The same WP login should work, but I created a new FTP account for the staging environment. The host and port are the same, just different user/pass.

- User: agcorp-mmarquiscreative-staging
- Pass: nAkl2sCEJ4yu
